version: '3'
services:
  app:
    build: .
    environment:
      - APP_DB_HOST=db
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
