---
logging:
  level:
    org:
      springframework:
        web: INFO
    de:
      wwestenbrink: INFO

spring:
  application:
    name: app
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${APP_DB_HOST:localhost}/app_db
    username: ${APP_DB_USERNAME:app_user}
    password: ${APP_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yml

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true